### ISSUE TITLE
Email notifications for new requests

### ISSUE THREAD

**Issue by bursteg** [Azure/azure-oss-portal#4]
GitHub notifications may get lost among the other hundred emails we get from GitHub. Please send email notifications to team maintainers or Org admins about requests that come in.

**Comment by jeffwilcox** [comment]
Are you not filtering emails well?

As long as you turn off random notifications, you should be fine.

**Comment by bursteg** [comment]
I've been through the same discussion with Azure CLA a while ago. People just want to be notified using emails that are not coming from GitHub.

**Comment by jeffwilcox** [comment]
OK. I'll talk with the engineers taking over the portal.

**Comment by jeffwilcox** [comment]
@bursteg : good news, this is in the next sprint!

**Comment by jeffwilcox** [comment]
This functionality has internally shipped to Microsoft customers including yourself. Let me know if you have any feedback, we'll massage and improve the messages (they are a little wordy now).

Eventually this work will be back-ported to the open source version, but since we use an alternate e-mail service internally, it is not ready for public release yet as it contains a bunch of random company-specific goo.

Thanks for your patience... hope this helps.
