### ISSUE TITLE
Email notifications to users who submit requests

### ISSUE THREAD

**Issue by bursteg** [Azure/azure-oss-portal#5]
We get a lot of questions about the status of a request. An email notification to the requester with the status of the request will be very helpful.

**Comment by jeffwilcox** [comment]
Hi,
Users already receive emails through GitHub. An at-mention is used, the standard communication people use for GitHub issues.

Are you asking to actually setup a service like SendGrid and send a second email?

**Comment by bursteg** [comment]
yes.

**Comment by bursteg** [comment]
Any update on this? I get pined daily on "what's the status of my request" and "Why wasn't I notified that my request was declined?"

**Comment by jeffwilcox** [comment]
Still waiting for the OSPO office to get the replacement portal online. This was supposed to launch already but has not.

**Comment by jeffwilcox** [comment]
This functionality has internally shipped to Microsoft customers including yourself. Let me know if you have any feedback, we'll massage and improve the messages (they are a little wordy now).

Eventually this work will be back-ported to the open source version, but since we use an alternate e-mail service internally, it is not ready for public release yet as it contains a bunch of random company-specific goo.

At this time there are 3 email situations:

1. At request time, the requester gets notified that their request will be reviewed.
2. At request time, approvers get e-mail to approve the request, including a direct link.
3. At decision time, the requester gets notified of the decision

If a GitHub tracking issue existed in the past for the request, it will be closed, but going forward requests will be e-mail only, removing the need for a tracking repo per org.

Thanks for your patience... hope this helps.
